const translations = {
  ar: {
    cashier: "الكاشير",
    accounting: "المحاسبة والمخازن",
    cashier: "الكاشير",
    accounting: "المحاسبة والمخازن",
    welcomeAccount: "مرحبًا بك في المحاسبة والمخازن",
    orders: "الطلبات",
    customers: "العملاء",
    products: "المنتجات",
    categories: "التصنيفات",
    units: "الوحدات",
    itemCard: "بطاقة الصنف",
    inventoryTitle: "المخازن ▸",
    inventoryItems: "مواد المخزون",
    storagePlaces: "أماكن التخزين",
    issue: "صرف",
    production: "انتاج",
    inventoryCheck: "جرد",
    transfer: "تحويلات",
    returnToStore: "مرتجع للمخزن",
    damagedReturns: "مرتجع توالف",
    suppliersTitle: "الموردون ▸",
    suppliers: "الموردون",
    purchase: "الشراء",
    returnToSupplier: "مرتجع للمورد",
    adminTitle: "الإدارة ▸",
    pendingStockMoves: "حركات مخزون معلقة",
    devices: "الأجهزة والكاشير",
    warehouseStaff: "موظفي المخازن",
    productionStaff: "موظفي الانتاج",
    branches: "الفروع",
    deliveryAreas: "مناطق التوصيل",
    deliveryPrices: "أسعار التوصيل",
    discounts: "خصومات",
    cashier: "الكاشير",
    accounting: "المحاسبة والمخازن",
    adminLogin: "تسجيل دخول المدير",
    enterCode: "أدخل رمز الدخول",
    loginBtn: "دخول",
    welcomeAccount: "مرحبًا بك في المحاسبة والمخازن",
        ordersPageTitle: "إدارة الطلبات",
    ordersList: "قائمة الطلبات",
    fromDate: "من تاريخ",
    toDate: "إلى تاريخ",
    allBranches: "جميع الفروع",
    allCashiers: "جميع الكاشيرات",
    allZones: "كل المناطق",
    filterBtn: "فلترة",
    downloadExcel: "📥 تحميل Excel",
    printAll: "🖨️ طباعة الكل",
    selectAll: "تحديد الكل",
    invoiceNo: "رقم الفاتورة",
    customerName: "اسم العميل",
    zone: "منطقة التوصيل",
    phone: "رقم الهاتف",
    dateTime: "التاريخ والوقت",
    cashierName: "الكاشير",
    branchName: "الفرع",
    netTotal: "صافي الفاتورة",
    deliveryFee: "قيمة التوصيل",
    total: "إجمالي الفاتورة",
    payment: "طريقة الدفع",
    actions: "إجراءات",
    edit: "تعديل",
    delete: "حذف",
    confirmDelete: "هل أنت متأكد من حذف هذه الفاتورة؟",
    deletedSuccessfully: "تم حذف الفاتورة بنجاح ✅",
    editNotice: "خاصية تعديل الطلب ستُفعل لاحقًا بعد بناء نموذج التعديل",
    orderTypes: "أنواع الطلب وطرق الدفع"
  },
  en: {
    cashier: "Cashier",
    accounting: "Accounting & Inventory",
    cashier: "Cashier",
    accounting: "Accounting & Inventory",
    welcomeAccount: "Welcome to Accounting & Inventory",
    orders: "Orders",
    customers: "Customers",
    products: "Products",
    categories: "Categories",
    units: "Units",
    itemCard: "Item Card",
    inventoryTitle: "Inventory ▸",
    inventoryItems: "Stock Materials",
    storagePlaces: "Storage Locations",
    issue: "Issue",
    production: "Production",
    inventoryCheck: "Inventory Check",
    transfer: "Transfers",
    returnToStore: "Return to Store",
    damagedReturns: "Damaged Returns",
    suppliersTitle: "Suppliers ▸",
    suppliers: "Suppliers",
    purchase: "Purchase",
    returnToSupplier: "Return to Supplier",
    adminTitle: "Administration ▸",
    pendingStockMoves: "Pending Stock Movements",
    devices: "Devices & Cashier",
    warehouseStaff: "Warehouse Employees",
    productionStaff: "Production Employees",
    branches: "Branches",
    deliveryAreas: "Delivery Zones",
    deliveryPrices: "Delivery Prices",
    discounts: "Discounts",
    cashier: "Cashier",
    accounting: "Accounting & Inventory",
    adminLogin: "Admin Login",
    enterCode: "Enter Access Code",
    loginBtn: "Login",
    welcomeAccount: "Welcome to Accounting & Inventory",
    ordersPageTitle: "Orders Management",
    ordersList: "Orders List",
    fromDate: "From Date",
    toDate: "To Date",
    allBranches: "All Branches",
    allCashiers: "All Cashiers",
    allZones: "All Zones",
    filterBtn: "Filter",
    downloadExcel: "📥 Download Excel",
    printAll: "🖨️ Print All",
    selectAll: "Select All",
    invoiceNo: "Invoice No.",
    customerName: "Customer Name",
    zone: "Delivery Zone",
    phone: "Phone Number",
    dateTime: "Date & Time",
    cashierName: "Cashier",
    branchName: "Branch",
    netTotal: "Net Amount",
    deliveryFee: "Delivery Fee",
    total: "Total Amount",
    payment: "Payment Method",
    actions: "Actions",
    edit: "Edit",
    delete: "Delete",
    confirmDelete: "Are you sure you want to delete this invoice?",
    deletedSuccessfully: "Invoice deleted successfully ✅",
    editNotice: "Edit feature will be activated later after edit form creation",
    orderTypes: "Order Types & Payment Methods"
  }
};
